### ISSUE TITLE
Feature request: reuse password tokens for their lifetime

### ISSUE THREAD

**Issue by matt-domsch-sp** [floor114/mysql2-aws_rds_iam#3]
First, thank you for this work. We'd like to use it to eliminate needing to manually manage and rotate mysql  passwords when in the AWS environment.

I'm concerned that because a new password token is generated on every point of need, that we will run into the AWS 200-per-second rate limit for our production uses, which will spin up dozens of ECS instances, each with upwards of 100 connections. This concern would be alleviated if password tokens were cached and reused until expiry, which is [what Amazon recommends](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/UsingWithRDS.IAMDBAuth.html#UsingWithRDS.IAMDBAuth.Limitations).

I opened a similar [feature request](https://github.com/haines/pg-aws_rds_iam/issues/688) with the haines/pg-aws_rds_iam project, who implemented token caching and reuse.  Since this project was inspired by the pg project, could something similar be added to this gem to cache and reuse tokens until expiry.

Full disclosure: I took a stab at [adding IAM support directly in the mysql2 gem.](https://github.com/brianmario/mysql2/pull/1381). Upstream maintainers haven't commented on it, and like the pg maintainer, may not want AWS-specific code in the gem like this, hence being in a gem as you have may be deemed the best approach.

**Comment by matt-domsch-sp** [comment]
The https://github.com/haines/pg-aws_rds_iam gem added support for token reuse in the new 0.7.0 release last week, via commit https://github.com/haines/pg-aws_rds_iam/commit/e551a07320b0f5e0a244eb1e57e7c49f15bc0765.  This may be a useful pattern for this gem as well.

**Comment by matt-domsch-sp** [comment]
PR: https://github.com/floor114/mysql2-aws_rds_iam/pull/4

**Comment by floor114** [comment]
Hey @matt-domsch-sp, thank you for the feature request. I was working on it over the weekends #5

**Comment by floor114** [comment]
@matt-domsch-sp, release it under [0.2.0](https://rubygems.org/gems/mysql2-aws_rds_iam/versions/0.2.0). 
Thanks again!

**Comment by matt-domsch-sp** [comment]
Thank you!
